memorylane-users/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :users

  get '/memories', to: 'memories#index'
  get '/memories/new', to: 'memories#new'
  get '/categories', to: 'memories#categories'
  get '/locations', to: 'memories#locations'

  get '/trips', to: 'trips#index'
  get '/trips/new', to: 'trips#new'
  post '/trips', to: 'trips#create'
  get '/trips/:id', to: 'trips#show'
  get '/trips/:id/edit', to: 'trips#edit'
  patch '/trips/:id', to: 'trips#update'
  delete '/trips/:id', to: 'trips#delete'

  get '/concerts', to: 'concerts#index'
  get '/concerts/new', to: 'concerts#new'
  post '/concerts', to: 'concerts#create'
  get '/concerts/:id', to: 'concerts#show'
  get '/concerts/:id/edit', to: 'concerts#edit'
  patch '/concerts/:id', to: 'concerts#update'
  delete '/concerts/:id', to: 'concerts#delete'

  get '/achievements', to: 'achievements#index'
  get '/achievements/new', to: 'achievements#new'
  post '/achievements', to: 'achievements#create'
  get '/achievements/:id', to: 'achievements#show'
  get '/achievements/:id/edit', to: 'achievements#edit'
  patch '/achievements/:id', to: 'achievements#update'
  delete '/achievements/:id', to: 'achievements#delete'
end

memorylane-users/app/models/achievement.rb
class Achievement < Memory
end

memorylane-users/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

memorylane-users/app/models/concert.rb
class Concert < Memory
  
end

memorylane-users/app/models/memory.rb
class Memory < ApplicationRecord
  before_save :set_default

  belongs_to :user
  self.inheritance_column = :category

  validates :category, presence: true

  has_attached_file :memoryphoto, styles: { large: "1200x1200>", medium: "600x600>", small: "100x100>", thumb: "34x34>" }, default_url: "/images/:style/concert-missing.jpg",
  :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
  :url => "/system/:attachment/:id/:style/:filename"
  validates_attachment_content_type :memoryphoto, content_type: /\Aimage\/.*\Z/

  scope :trips, -> { where(category: 'Trip') }
  scope :concerts, -> { where(category: 'Concert') }
  scope :achievements, -> { where(category: 'Achievement') }

  def self.categories
    %w(Trip Concert Achievement)
  end

  def set_default
    self.date = Time.now unless self.date
  end
end

memorylane-users/app/models/trip.rb
class Trip < Memory
end

memorylane-users/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memories
  delegate :trips, :concerts, :achievements, to: :memories
  validates :email, presence: true

  has_attached_file :avatar, styles: { medium: "600x600>", small: "100x100>", thumb: "34x34>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_attached_file :coverphoto, styles: { large: "1200x600>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :coverphoto, content_type: /\Aimage\/.*\Z/
end

memorylane-users/app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  def index
    @achievements = Achievement.all.achievements.order("date desc")
  end

  def show
    @achievement = Achievement.find_by(id: params[:id])
  end

  def new
    @achievement = current_user.achievements.build
    render 'new'
  end

  def create
    @achievement = current_user.achievements.create(achievement_params)
    if @achievement.save
      redirect_to '/achievements'
    else
      render action: 'new'
    end
  end

  def edit
    @achievement = Achievement.find(params[:id])
  end

  def update
    @achievement = Achievement.find(params[:id])
    if @achievement.update(achievement_params)
      redirect_to '/achievements'
    else
      render action: 'index'
    end
  end

  def delete
    @achievement = Achievement.find(params[:id])
    @achievement.destroy
    if @achievement.destroy
      redirect_to '/achievements'
    else
      render action: 'index'
    end
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :achievement, :reward, :date, :location, :friends, :notes, :memoryphoto, :user_id)
  end

end

memorylane-users/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!, only: :Show

  def show
    @user = User.find(params[:id])
    render 'users/show'
  end
end

memorylane-users/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :avatar, :coverphoto])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :avatar, :coverphoto])
    devise_parameter_sanitizer.permit(:memory, keys: [:memoryphoto])
  end
end

memorylane-users/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
    @concerts = Concert.all.concerts.order("date desc")
  end

  def show

    @concert = Concert.find_by(id: params[:id])

  end

  def new
    @concert = current_user.concerts.build
    render 'new'
  end

  def create
    @concert = current_user.concerts.create(concert_params)
    if @concert.update(concert_params)
      redirect_to '/concerts'
    else
      @concert.destroy
      render action: 'new'
    end
  end

  def edit
    @concert = Concert.find_by(id: params[:id])
  end

  def update
    @concert = Concert.find(params[:id])
    if @concert.update(concert_params)
      redirect_to '/concerts'
    else
      render action: 'index'
    end
  end

  def delete
    @concert = Concert.find(params[:id])
    @concert.destroy
    if @concert.destroy
      redirect_to '/concerts'
    else
      render action: 'index'
    end
  end

  private

  def concert_params
    params.require(:concert).permit(:title, :artist, :location, :date, :venue, :friends, :notes, :memoryphoto, :user_id)
  end

end

memorylane-users/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

memorylane-users/app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  def index
    @memories = current_user.memories.order("date desc")
  end

  def show
  end

  def new
  end

  def edit
  end

  def create

  end

  def update

  end

  def destroy

  end

end

memorylane-users/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all.trips.order("date desc")
  end

  def show
    @trip = Trip.find_by(id: params[:id])
  end

  def new
    @trip = current_user.trips.build
    render 'new'
  end

  def create
    @trip = current_user.trips.build(trip_params)
    @trip.save
    if @trip.save
      redirect_to '/trips'
    else
      render action: 'new'
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to '/trips'
    else
      render action: 'index'
    end
  end

  def delete
    @trip = Trip.find(params[:id])
    @trip.destroy
    if @trip.destroy
      redirect_to '/trips'
    else
      render action: 'index'
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :location, :destination, :date, :enddate, :friends, :notes, :memoryphoto, :user_id)
  end
end

memorylane-users/app/helpers/achievements_helper.rb
module AchievementsHelper
end

memorylane-users/app/helpers/admin_helper.rb
module AdminHelper
end

memorylane-users/app/helpers/application_helper.rb
module ApplicationHelper
end

memorylane-users/app/helpers/concerts_helper.rb
module ConcertsHelper
end

memorylane-users/app/helpers/home_helper.rb
module HomeHelper
end

memorylane-users/app/helpers/memories_helper.rb
module MemoriesHelper
  def memory_button_color(memory_type)
    case memory_type
    when 'Trip'
      'green'
    when 'Concert'
      'blue'
    when 'Achievement'
      'pink'
    end
  end

  def memory_pin_name(memory_type)
    case memory_type
    when 'Trip'
      'icons/pin-map.svg'
    when 'Concert'
      'icons/pin-microphone.svg'
    when 'Achievement'
      'icons/pin-medal.svg'
    else
      'memoryrandom'
    end
  end
end

memorylane-users/app/helpers/trips_helper.rb
module TripsHelper
end

memorylane-users/app/views/achievements/edit.html.erb
<div class="row header achievement-header">
  <%= image_tag('icons/icon-medal-fill.svg', class: "memory-icon") %>
</div>

<div class="row title-bar title-bar-pink">
  <h3>Editing <%= @achievement.title %></h3>
</div>

<div class="row">
  <%= form_for @achievement, as: :achievement, url: {action: 'update'} do |f| %>
    <div class="field">
      <%= f.label(:title, 'Memory title') %><br>
      <%= f.text_field(:title) %>
    </div>

    <div class="field">
      <%= f.label(:achievement) %><br>
      <%= f.text_field(:achievement) %>
    </div>

    <div class="field">
      <%= f.label(:reward) %><br>
      <%= f.text_field(:reward) %>
    </div>

    <div class="field">
      <%= f.label(:date) %><br>
      <%= f.date_field(:date) %>
    </div>

    <div class="field">
      <%= f.label(:location) %><br>
      <%= f.text_field(:location) %>
    </div>

    <div class="field">
      <%= f.label(:friends) %><br>
      <%= f.text_field(:friends) %>
    </div>

    <div class="field">
      <%= f.label(:notes) %><br>
      <%= f.text_area(:notes) %>
    </div>

    <div class="field upload">
      <%= f.label :memoryphoto %>:
      <%= f.file_field(:memoryphoto) %>
    </div>

    <div class="field hidden">
      <%= f.label(:category) %><br>
      <%= select(:category, Memory.categories.map {|r| [r.humanize, r.camelcase]}, {}, disabled: @category != "Memory") %>
    </div>
    <div class="actions submit submit-pink">
      <%= submit_tag("UPDATE MEMORY") %>
    </div>
  <% end %>
</div>

memorylane-users/app/views/achievements/index.html.erb
<div class="row header achievement-header">
  <%= image_tag('icons/icon-medal-fill.svg', class: "memory-icon") %>
</div>

<div class="row title-bar title-bar-pink">
  <h3>My achievements</h3>
</div>

<div class="row cards">
  <% @achievements.each do |achievement| %>
    <% if achievement.user_id == current_user.id %>
      <div class="col-lg-4 col-md-6 col-sm-12 memory-card">
        <%= image_tag('icons/pin-medal.svg', class: "memory-pin") %>
        <div class="memory-box">
          <h4><%= achievement.title.upcase %></h4>
          <p><i class="fa fa-map-marker" aria-hidden="true"></i> <%= achievement.location %></p>
          <p><i class="fa fa-trophy" aria-hidden="true"></i> <%= achievement.reward %></p>
          <p><i class="fa fa-calendar-o" aria-hidden="true"></i> <%= achievement.date.try(:to_formatted_s, :long) %></p>
          <div class="btn btn-pink">
            <%= link_to 'VIEW MEMORY', "/#{achievement.category.downcase.pluralize}/#{achievement.id}" %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<div class="row">
  <%= link_to 'Add achievement', "/achievements/new" %><br>
  <%= link_to 'All memories', "/memories" %>
</div>

memorylane-users/app/views/achievements/new.html.erb
<div class="row header achievement-header">
  <%= image_tag('icons/icon-medal-fill.svg', class: "memory-icon") %>
</div>

<div class="row title-bar title-bar-pink">
  <h3>Add new achievement</h3>
</div>

<div class="row">
  <%= form_for @achievement, as: :achievement, url: {action: 'create'} do |f| %>
    <div class="field">
      <%= f.label(:title, 'Memory title') %><br>
      <%= f.text_field(:title) %>
    </div>

    <div class="field">
      <%= f.label(:achievement) %><br>
      <%= f.text_field(:achievement) %>
    </div>

    <div class="field">
      <%= f.label(:reward) %><br>
      <%= f.text_field(:reward) %>
    </div>

    <div class="field">
      <%= f.label(:date) %><br>
      <%= f.date_field(:date) %>
    </div>

    <div class="field">
      <%= f.label(:location) %><br>
      <%= f.text_field(:location) %>
    </div>

    <div class="field">
      <%= f.label(:friends) %><br>
      <%= f.text_field(:friends) %>
    </div>

    <div class="field">
      <%= f.label(:notes) %><br>
      <%= f.text_area(:notes) %>
    </div>

    <div class="field upload">
      <%= f.label :memoryphoto %>:
      <%= f.file_field(:memoryphoto) %>
    </div>

    <div class="field hidden">
      <%= f.label(:category) %><br>
      <%= select(:category, Memory.categories.map {|r| [r.humanize, r.camelcase]}, {}, disabled: @category != "Memory") %>
    </div>
    <div class="actions submit submit-pink">
      <%= submit_tag("CREATE MEMORY") %>
    </div>
  <% end %>
</div>

memorylane-users/app/views/admin/show.html.erb
<div>
   <% if user_signed_in? %>
     <p><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></p>
   <% else %>
     <p><%= link_to('Login', new_user_session_path)  %></p>
   <% end %>
   <p><%= link_to('Signup', new_user_registration_path) %></p>
 </div>

memorylane-users/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memory Lane</title>
    <%= favicon_link_tag %>
    <script src="https://use.fontawesome.com/932dea43d4.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <!-- Page Content -->
    <div id="wrapper">
      <%= render 'partials/sidebar' %>

      <!-- Page content -->
      <div id="page-content-wrapper">
        <nav class="navbar navbar-default">
          <%= link_to memories_path do %><%= image_tag 'logo_thick.svg' %><% end %>
        </nav>
    <% end %>
        <%= yield %>
    <% if user_signed_in? %>
        <nav class="navbar navbar-default navbar-fixed-bottom">
            <div class="col-sm-15 col-xs-15">
              <%= link_to root_path do %><svg class="tab-icon" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 179.49 198.24"><defs><style>.cls-1{fill:#324152;stroke:#324152;stroke-miterlimit:10;stroke-width:4px;}</style></defs><title>tab-profile</title><path class="cls-1" d="M177,150.83c-10.13-4.23-34.2-12.51-49-16.88-1.26-.4-1.46-0.46-1.46-5.71,0-4.34,1.78-8.71,3.52-12.41A63.59,63.59,0,0,0,135,99c2.24-2.61,5.3-7.75,7.26-17.55,1.72-8.64.92-11.78-.23-14.73-0.12-.31-0.24-0.62-0.33-0.92-0.43-2,.16-12.55,1.63-20.71,1-5.6-.27-17.51-8-27.36-4.87-6.23-14.19-13.87-31.21-14.92H94.81C78.08,3.86,68.75,11.51,63.89,17.74c-7.71,9.86-9,21.77-8,27.36,1.49,8.17,2.08,18.69,1.66,20.67a7.61,7.61,0,0,1-.34,1c-1.14,2.95-1.95,6.09-.21,14.73,2,9.8,5,14.94,7.28,17.54a62.92,62.92,0,0,0,4.93,16.83c1.38,2.94,2,6.94,2,12.59,0,5.25-.2,5.32-1.38,5.69-15.3,4.52-39.66,13.34-48.74,17.32-7.19,3.09-9,8.64-9,13.64v23.09c0,3.27,1.95,8.85,9,8.85l68.2,0h21.17l68.2,0c7,0,9-5.59,9-8.86V165C187.68,160,184.23,153.91,177,150.83Zm1.37,36.91-67.87,0H89.37l-67.92,0V165.09c0-2.8.81-4.05,3.42-5.17,8.75-3.83,32.93-12.57,47.83-17,7.82-2.48,7.82-9.43,7.82-14.5,0-7-.93-12.3-2.92-16.53a53.43,53.43,0,0,1-4.13-14.1L73.1,95.07,71.29,93c-1-1.15-3.49-4.74-5.2-13.32-1.34-6.69-.75-8.23-0.27-9.47a17.15,17.15,0,0,0,.71-2.08l0-.2,0-.2c0.93-4.36-.33-17.28-1.61-24.26-0.59-3.21.15-12.33,6.15-20C74.84,18.72,82,12.95,95.12,12h8.74c10.73,0.72,18.89,4.55,24.23,11.38,6,7.68,6.75,16.8,6.17,20-1.3,7.16-2.52,19.87-1.58,24.29l0.07,0.34,0.1,0.33c0.14,0.47.31,0.95,0.5,1.42L133.42,70h0c0.52,1.35,1.12,2.87-.22,9.57C131.5,88.2,129,91.81,128,93l-1.8,2.09-0.36,2.73a54.11,54.11,0,0,1-4.12,14.12c-2.18,4.63-4.4,10.19-4.4,16.34,0,5.08,0,12,8.09,14.57,14.46,4.26,38.26,12.46,48,16.51,3.68,1.58,5.05,4.34,5.05,5.71Z" transform="translate(-10.2 -0.79)"/></svg> <% end %>
            </div>

            <div class="col-sm-15 col-xs-15">
              <%= link_to memories_path do %><svg class="tab-icon" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 170.53 199.09"><defs><style>.cls-1{fill:#324152;stroke:#324152;stroke-miterlimit:10;stroke-width:4px;}</style></defs><title>tab-memories</title><path class="cls-1" d="M16.67,86.89l0,111,64.74,0,0-64.74,37,0,0,64.74,64.74,0,0-111L99.88,3.61ZM173.95,188.56l-46.24,0,0-55.49v-9.25h-9.25l-37,0H72.18v9.25l0,55.49-46.24,0,0-97.91,74-74,74,74Z" transform="translate(-14.67 -0.78)"/></svg> <% end %>
            </div>

            <div class="col-sm-15 col-xs-15">
              <%= link_to memories_new_path do %><svg class="tab-icon" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 215.48 215.48"><defs><style>.cls-1,.cls-2{fill:#324152;stroke:#324152;stroke-width:4px;}.cls-1{stroke-miterlimit:10;}.cls-2{stroke-linejoin:round;}</style></defs><title>tab-plus</title><path class="cls-1" d="M109,3.26A105.74,105.74,0,1,0,214.74,109,105.73,105.73,0,0,0,109,3.26Zm0.08,203A97.28,97.28,0,1,1,206.28,109,97.39,97.39,0,0,1,109,206.28Z" transform="translate(-1.26 -1.26)"/><polygon class="cls-2" points="111.94 44.3 103.49 44.3 103.51 103.51 44.58 103.54 44.58 112 103.51 111.97 103.54 170.91 112 170.9 111.97 111.97 171.19 111.94 171.18 103.49 111.97 103.51 111.94 44.3"/></svg> <% end %>
            </div>

            <div class="col-sm-15 col-xs-15">
              <%= link_to root_path do %><svg class="tab-icon" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 198.25 198.17"><defs><style>.cls-1{fill:#324152;stroke:#324152;stroke-linejoin:round;stroke-width:4px;}</style></defs><title>tab-search</title><path class="cls-1" d="M197.12,186.9l-56-56a78.14,78.14,0,1,0-10.17,10.18l56,56ZM11.1,81.06A69.89,69.89,0,1,1,81,150.92,70,70,0,0,1,11.1,81.06Z" transform="translate(-0.88 -0.92)"/></svg><% end %>
            </div>

            <div class="col-sm-15 col-xs-15">

              <a href="#menu-toggle" id="menu-toggle"><svg class="tab-icon" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 199.03 43.01"><defs><style>.cls-1{fill:#324152;stroke:#324152;stroke-miterlimit:10;stroke-width:4px;}</style></defs><title>tab-dots</title><path class="cls-1" d="M22,80.5A19.5,19.5,0,1,0,41.49,100,19.5,19.5,0,0,0,22,80.5ZM22,113a13,13,0,1,1,13-13A13,13,0,0,1,22,113Z" transform="translate(-0.48 -78.5)"/><path class="cls-1" d="M178,80.5a19.5,19.5,0,1,0,19.5,19.5A19.5,19.5,0,0,0,178,80.5ZM178,113a13,13,0,1,1,13-13A13,13,0,0,1,178,113Z" transform="translate(-0.48 -78.5)"/><path class="cls-1" d="M100,80.5A19.5,19.5,0,1,0,119.5,100,19.5,19.5,0,0,0,100,80.5ZM100,113a13,13,0,1,1,13-13A13,13,0,0,1,100,113Z" transform="translate(-0.48 -78.5)"/></svg></a>
            </div>
        </nav>
        <!-- Bottom tap bar end -->
        </div>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->
<% end %>

      </div>
    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
  </body>
</html>

memorylane-users/app/views/memories/categories.html.erb
<div class="row main-wrap">
  <h3>Categories</h3>
  <div class="row nopad-top-bottom">
    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to concerts_path do %><%= image_tag('icons/icon-microphone.svg', class: "memory-icon") %><p>CONCERTS</p><% end %>
    </div>

    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to trips_path do %><%= image_tag('icons/icon-map-pin.svg', class: "memory-icon") %><p>TRIPS</p><% end %>
    </div>

    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to achievements_path do %><%= image_tag('icons/icon-medal.svg', class: "memory-icon") %><p>ACHIEVEMENTS</p><% end %>
    </div>
  </div>

  <div class="row nopad-top-bottom">
    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to concerts_path do %><%= image_tag('icons/icon-song.svg', class: "memory-icon") %><p>SONG</p><% end %>
    </div>

    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to trips_path do %><%= image_tag('icons/icon-lightbulb.svg', class: "memory-icon") %><p>IDEA</p><% end %>
    </div>

    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to achievements_path do %><%= image_tag('icons/icon-ticket.svg', class: "memory-icon") %><p>EVENT</p><% end %>
    </div>
  </div>
</div>

memorylane-users/app/views/memories/index.html.erb
<div class="row profile-header" style="background-image: url('<%= current_user.coverphoto.url %>'); background-size: cover; background-position: center;">
  <%= image_tag(current_user.avatar.url(:small)) %>
  <h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
</div>

<div class="row title-bar title-bar-pink">
  <h3>MY MEMORY LANE</h3>
</div>

<div class="row cards">
  <% @memories.each do |memory| %>
    <% if memory.user_id == current_user.id %>
      <div class="col-lg-4 col-md-6 col-sm-12 memory-card">
        <%= image_tag(memory_pin_name(memory.category), class: "memory-pin") %>
        <div class="memory-box">
          <h4><%= memory.title %></h4>
          <p><i class="fa fa-map-marker" aria-hidden="true"></i> <%= memory.location %></p>
          <p><i class="fa fa-calendar-o" aria-hidden="true"></i> <%= memory.date.try(:to_formatted_s, :long)  %></p>
          <button class='btn btn-<%= memory_button_color(memory.category) %>'>
            <%= link_to 'VIEW MEMORY', "/#{memory.category.downcase.pluralize}/#{memory.id}" %>
          </button>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<!-- <div class="row">
  <%= link_to('Add memory', memories_new_path)  %>
  <% if user_signed_in? %>
    <p><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></p>
    <% else %>
    <p><%= link_to('Login', new_user_session_path)  %></p>
  <% end %>
  <p><%= link_to('View profile', root_path)  %></p>
</div> -->

memorylane-users/app/views/memories/locations.html.erb
<div class="google-map">
  <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d10348739.051507805!2d3.6929342875000044!3d50.709778894064335!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1470329362427" width="100%" height="80vh" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

memorylane-users/app/views/memories/new.html.erb
<div class="row main-wrap">
  <h3>Add new memory</h3>
  <div class="row nopad-top-bottom">
    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to concerts_new_path do %><%= image_tag('icons/icon-microphone.svg', class: "memory-icon") %><p>CONCERT</p><% end %>
    </div>

    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to trips_new_path do %><%= image_tag('icons/icon-map-pin.svg', class: "memory-icon") %><p>TRIP</p><% end %>
    </div>

    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to achievements_new_path do %><%= image_tag('icons/icon-medal.svg', class: "memory-icon") %><p>ACHIEVEMENT</p><% end %>
    </div>
  </div>

  <div class="row nopad-top-bottom">
    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to concerts_new_path do %><%= image_tag('icons/icon-song.svg', class: "memory-icon") %><p>SONG</p><% end %>
    </div>

    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to trips_new_path do %><%= image_tag('icons/icon-lightbulb.svg', class: "memory-icon") %><p>IDEA</p><% end %>
    </div>

    <div class="col-sm-4 col-xs-4 add-memory">
      <%= link_to achievements_new_path do %><%= image_tag('icons/icon-ticket.svg', class: "memory-icon") %><p>EVENT</p><% end %>
    </div>
  </div>
</div>